### ISSUE TITLE
Users Assigned on Tasks Not Removed on Leave Project or Remove Member

### ISSUE THREAD

**Issue by ElenaArnold** [yismailuofa/kraken-frontend#150]
- In the SRS we say users will be removed as assignee to task they are assigned to when they leave a project
- In the SRS we say users will be removed as assignee to task they are assigned to when they are removed from a project

**Comment by yismailuofa** [comment]
Tried a fix [here](https://github.com/yismailuofa/kraken-backend/commit/55ad3641d0e417795b37e502d32a7799ff1b4b29), let me know if it worked.

**Comment by ElenaArnold** [comment]
> Tried a fix [here](https://github.com/yismailuofa/kraken-backend/commit/55ad3641d0e417795b37e502d32a7799ff1b4b29), let me know if it worked.

It worked for removing the user on tasks when they leave the project, but it did not remove the user from QA tasks and the user is still not removed from either QA or the main task when the project admin removes the user from the project.

**Comment by yismailuofa** [comment]
Oh I know what went wrong

**Comment by yismailuofa** [comment]
[try 2 ](https://github.com/yismailuofa/kraken-backend/commit/e51e8a871fa035380c8c74e119c5bd05a474d90e)🥼

**Comment by ElenaArnold** [comment]
Works!
