### ISSUE TITLE
Document Code & Setup Run Instructions

### ISSUE THREAD

**Issue by ElenaArnold** [yismailuofa/kraken-frontend#157]
- Document the code as required by the System Implementation Instructions
![image](https://github.com/yismailuofa/kraken-frontend/assets/114539416/da035afb-6820-472c-ba52-d5e9722c20fd)

- Write run instructions:
- Prerequisites: install npm "here/url"
- Go to this “url” or run npm install then npm start
- Include link to test suite documents in final submission folder

**Comment by yismailuofa** [comment]
[Backend Commit](https://github.com/yismailuofa/kraken-backend/commit/5d711be89869c97de96c2fc352a884f483be78b6)
